dist: xenial
sudo: false

language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7

cache: pip

env:
- DJANGO=1.11
- DJANGO=2.0
- DJANGO=2.1
- DJANGO=master

matrix:
  fast_finish: true
  include:
  - python: 3.7
    env: TOXENV=flake8
  exclude:
  - python: 2.7
    env: DJANGO=2.0
  - python: 2.7
    env: DJANGO=2.1
  - python: 3.4
    env: DJANGO=2.1
  allow_failures:
  - env: DJANGO=master
install:
  - travis_retry pip install -U tox-travis

script:
- tox
