# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheDynamicVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(max_length=50)),
                ('cache_name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cachedynamicversion',
            unique_together=set([('cache_type', 'cache_name')]),
        ),
    ]
